Feat/firebase
kphutiyagae/VacationVault pull request #2
Opened 2023-03-25 12:21 UTC by kphutiyagae

* Added Anguar Fire.
* Added firebase config file.

2023-03-25 13:12 UTC, CharelMarais requested changes
Major security flaw with adding the environments to git.  Please see my comment.

2023-03-25 13:12 UTC, CharelMarais commented on src/environments/environment.ts
This is sensitive information giving access to your backend and should not be pushed to git.

You should re-generate the api config file, and then add it to gitignore.

2023-03-25 13:15 UTC, kphutiyagae commented on src/environments/environment.ts
Thanks for the heads up, I forgot to add it to the gitignore. Will do

2023-03-27 07:18 UTC, CharelMarais approved these changes

2023-03-27 08:19 UTC, merged