Feat/login-signup
kphutiyagae/VacationVault pull request #8
Opened 2023-04-06 17:13 UTC by kphutiyagae

* Implemented reactive forms for login and signup components.
* Added modal for user feedback and Validators.
* Added responsive design to components.

2023-04-07 10:38 UTC, CharelMarais requested changes
The code looks good but you have your environment file showing.

2023-04-07 10:38 UTC, CharelMarais commented on src/app/environments/environment.ts
What do we have here, some sensitive information...

2023-04-08 11:32 UTC, kphutiyagae commented on src/app/environments/environment.ts
Haha!
Git keeps tracking this file. Anyways, information was regenerated and removed from Git as requested.

2023-04-08 15:52 UTC, CharelMarais approved these changes
There we go

2023-04-08 16:59 UTC, merged